name       : python-pkginfo
version    : 1.7.1
release    : 1
source     :
    - https://pypi.io/packages/source/p/pkginfo/pkginfo-1.7.1.tar.gz : e7432f81d08adec7297633191bbf0bd47faf13cd8724c3a13250e51d542635bd
license    : MIT
component  : programming.python
summary    : Query metadatdata from sdists / bdists / installed packages.
description: |
    Query metadatdata from sdists / bdists / installed packages.
build      : |
    %python3_setup
install    : |
    %python3_install
