name       : python-pkginfo
version    : 1.9.6
release    : 2
source     :
    - https://pypi.io/packages/source/p/pkginfo/pkginfo-1.9.6.tar.gz : 8fd5896e8718a4372f0ea9cc9d96f6417c9b986e23a4d116dda26b62cc29d046
license    : MIT
component  : programming.python
summary    : Query metadatdata from sdists / bdists / installed packages.
description: |
    Query metadatdata from sdists / bdists / installed packages.
build      : |
    %python3_setup
install    : |
    %python3_install
